version: "3.3"

services:
  database_rent:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=rentslz
    volumes:
      - pgdata:/data/postgres
  # app:
  #   build: .
  #   container_name: rentslz
  #   volumes:
  #     - .:/usr/app
  #   ports:
  #     - "3333:3333"
  #   network_mode: host
    

volumes:
  pgdata:
    driver: local
